# Generated by Django 6.0.3 on 2026-08-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blogpost'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category'], name='api_blogpos_categor_83b24e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published'], name='api_blogpos_publish_2cfd99_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='api_message_is_read_d765e9_idx'),
        ),
    ]
